(function (global) {
  'use strict';
  const block = values => ({values,rms:Math.sqrt(values.reduce((t,v)=>t+v*v,0)/values.length),mean:values.reduce((t,v)=>t+v,0)/values.length,min:Math.min(...values),max:Math.max(...values),negative:values.filter(v=>v<0).length/values.length});
  function value(l,r,c,type){const z=Math.sin((r+1)*12.9898+(c+1)*78.233+l*4.193);if(type==='weight')return .024*z+.012*Math.sin(r*.3+c*.15+l*.09);if(type==='gradient')return .0005*z+.006*Math.exp(-Math.pow((r-8)/3,2)-Math.pow((c-16)/3,2))*Math.exp(-Math.pow((l-18)/6,2));return .4*z+1.1*Math.sin(c*.7+l*.04)*Math.exp(-Math.pow((r-12)/3,2))+.15*Math.sin(r*.5)}
  function pack(values){const stats=Array.from({length:256},(_,i)=>{const v=[];for(let r=0;r<4;r++)for(let c=0;c<4;c++)v.push(values[(Math.floor(i/16)*4+r)*64+i%16*4+c]);return block(v)});return {stats,blocks:stats.map(x=>x.rms),rms:Math.sqrt(values.reduce((a,x)=>a+x*x,0)/4096)}}
  function flatten(d){return Array.from({length:4096},(_,i)=>{const r=Math.floor(i/64),c=i%64;return d.stats[Math.floor(r/4)*16+Math.floor(c/4)].values[r%4*4+c%4]})}
  function makeData(type){return Array.from({length:49},(_,l)=>{const center=type==='weight'?34:type==='gradient'?18:29,gain=1+(type==='gradient'?2.8:1.25)*Math.exp(-Math.pow((l-center)/2.2,2));return pack(Array.from({length:4096},(_,i)=>value(l,Math.floor(i/64)*24/64,(i%64)*24/64,type)*gain))})}
  const baseline={weight:makeData('weight'),gradient:makeData('gradient'),activation:makeData('activation')},targets={weight:34,gradient:18,activation:29},observed={};
  for(const type of Object.keys(baseline))observed[type]=baseline[type].map((d,l)=>pack(flatten(d).map((v,i)=>{const r=Math.floor(i/64),c=i%64;return l===targets[type]&&r>=24&&r<32&&c>=32&&c<40?v*({weight:12,gradient:18,activation:12}[type]):v})));
  const propagation=[],propagationMeta=[];let delta=new Array(4096).fill(0);const source=18,scale=3.6*Math.max(...flatten(baseline.activation[source]).map(Math.abs));
  for(let l=0;l<49;l++){let gain=1;if(l===source)delta=delta.map((_,i)=>{const r=Math.floor(i/64),c=i%64;return r>=24&&r<32&&c>=32&&c<40?scale*(.85+.15*Math.cos(c)):0});else if(l>source){gain=l<=22?1.25:l<=25?.9:.58;const previous=delta;delta=previous.map((v,i)=>gain*(.85*v+.15*previous[Math.floor(i/64)*64+(i%64+63)%64]))}propagation.push(pack(flatten(baseline.activation[l]).map((v,i)=>v+delta[i])));propagationMeta.push({gain,deltaRms:Math.sqrt(delta.reduce((a,x)=>a+x*x,0)/4096),affected:delta.filter(x=>Math.abs(x)>1e-9).length})}
  const hiddenCache=new Map();
  function hidden(boundary){if(hiddenCache.has(boundary))return hiddenCache.get(boundary);const values=[],references=[];let sum=0,sq=0,refSq=0,peak=0,alerts=0,gain=boundary<19?0:boundary<=23?1.5*Math.pow(1.17,boundary-19):1.5*Math.pow(1.17,4)*Math.pow(.79,boundary-23);for(let r=0;r<64;r++)for(let c=0;c<64;c++){const ref=.55*Math.sin(r*.37+c*.19+boundary*.035)+.34*Math.cos(c*.51-r*.11)+.08*Math.sin(r*9.1+c*5.7),v=ref+gain*Math.exp(-(((r-27)/5)**2+((c-39)/6)**2));values.push(v);references.push(ref);sum+=v;sq+=v*v;refSq+=ref*ref;peak=Math.max(peak,Math.abs(v));if(Math.abs(v-ref)>1)alerts++}const result={values,references,rms:Math.sqrt(sq/4096),referenceRms:Math.sqrt(refSq/4096),mean:sum/4096,peak,alerts};hiddenCache.set(boundary,result);return result}
  const layerDataSource={
    async queryTensor(context){await Promise.resolve();if(!baseline[context.mode])return {status:'missing',reason:'not-applicable',message:'该观测口径暂无数据',context};const references=baseline[context.mode],layers=context.scenario==='normal'?references:context.scenario==='propagation'&&context.mode==='activation'?propagation:observed[context.mode];return {status:'ready',context,sampling:{rows:64,columns:64,logicalShape:context.mode==='activation'?[32768,1024]:[1024,2560],strategy:'uniform-grid',scope:'sample-only'},statistics:{rms:'sqrt(mean(x^2))',anomaly:'non-finite-or-abs-over-reference-max',thresholdMultiplier:3,referenceStep:1279},layers,references,limits:references.map(d=>3*Math.max(...d.stats.map(s=>Math.max(Math.abs(s.min),Math.abs(s.max))))),propagation:context.scenario==='propagation'&&context.mode==='activation'?propagationMeta:null}},
    async queryHidden(context,boundary){await Promise.resolve();if(boundary<0||boundary>context.layerCount)return {status:'missing',reason:'not-collected',message:'尚未采集此边界数据',context};return hidden(boundary)}
  };
  global.LayerAtlasData={layerDataSource};
})(window);
